language: objective-c
os: osx
osx_image: xcode9
script:
  - gem install xcpretty-travis-formatter
  - brew update
  - brew tap Homebrew/bundle
  - brew bundle
  #- set -o pipefail
  - ./build.sh
  #- xcodebuild -workspace "$WORKSPACE" -list

  # Build and test Framework in Debug
  #- xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty

  # Build Framework in ReleaseTest
  #- xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration ReleaseTest ONLY_ACTIVE_ARCH=NO build | xcpretty

  # Build Example in Debug if specified
  #- xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty

  # Run `pod lib lint` if specified
  #- if [ $POD_LINT == "YES" ]; then
  #    pod lib lint;
  #  fi

  - xcodebuild -project SwiftVer.xcodeproj -scheme "SwiftVer macOS" -destination 'platform=OS X,arch=x86_64' -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -cF macOS -X xcodeplist
  - xcodebuild -project SwiftVer.xcodeproj -scheme "SwiftVer iOS" -destination "platform=iOS Simulator,name=iPhone 7 Plus,OS=11.0" -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -cF iOS -X xcodeplist
  - xcodebuild -project SwiftVer.xcodeproj -scheme "SwiftVer tvOS" -destination "platform=tvOS Simulator,name=Apple TV 1080p,OS=11.0" -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -cF tvOS -X xcodeplist
  #- ruby ./Tests/CheckCocoaPodsQualityIndexes.rb SwiftVer
