language: objective-c
os: osx
osx_image: xcode11.3
script:
  - gem install xcpretty-travis-formatter cocoapods
  - npm install -g doctoc
  - brew update
  - brew tap Homebrew/bundle
  - brew bundle
  #- ./build.sh

  # Run `pod lib lint` if specified
  - pod lib lint

  - xcodebuild -project SwiftVer.xcodeproj -scheme "SwiftVer macOS" -destination 'platform=OS X,arch=x86_64' -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -cF macOS -X xcodeplist -g Tests 
  - xcodebuild -project SwiftVer.xcodeproj -scheme "SwiftVer iOS" -destination "platform=iOS Simulator,name:iPhone 11 Pro Max,OS=13.3" -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -cF iOS -X xcodeplist -g Tests
  - xcodebuild -project SwiftVer.xcodeproj -scheme "SwiftVer tvOS" -destination "platform=tvOS Simulator,name=Apple TV,OS=13.3" -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -cF tvOS -X xcodeplist -g Tests
  #- ruby ./Tests/CheckCocoaPodsQualityIndexes.rb SwiftVer
